### PR TITLE
Closes #76 - Updates readme to include the style guide.

### LINKED ISSUE #76: Find Kotlin coding bible.
Find a Kotlin naming conventions guide that we will use throughout our project. Update the README with a link to the guide.
DoD: A working link to the Kotlin styleguide is added to the README file.

### PR DESCRIPTION
**Pull request by silvioguiso**

### CODE REVIEW

**Comment by gomezfox** [comment]
Would it be appropriate to import this linked files into the project?  This would provide a snapshot in time of the guide that would be available offline within the branches, and would make it immune to changes that might occur until they are approved.

**Comment by silvioguiso** [comment]
I was thinking about that but at the same time I had conflicting feelings. As developers we are working on an ever-changing environment and nothing is set in stone. That's why I decided to post the links instead of a snapshot. But if you have good arguments against it we can discuss.

**Comment by gomezfox** [comment]
Understood, but I believe it would be useful if they existed within the project.  Quick access is one benefit.  One wouldn't need to leave Android Studio to refer to them, and offline access is sometimes necessary.  The way I see it, we should have our own, customizable design standards files within the project, and anyone outside the team would have the exact design doc from which we are working. 

As far as updates, it would give us control over when to update it ourselves--such as when an appropriate time for a refactor presents itself (we wouldn't want these to be implemented "midstream").  Also, there may be extensions and/or modifications that we, as a team decide on.

**Comment by silvioguiso** [comment]
Ok, we, as a team, will discuss the pros and cons tomorrow and make a decision on how we will proceed.

**Pull request closed without merging**
